[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { features = ["serde", "v4"], version = "1.10.0" }
rocket = { features = ["json"], version = "0.5.1" }
